### ISSUE TITLE
Docker file execution

### ISSUE THREAD

**Issue by izhidov** [fguiet/automationserver-v2#1]
Step 17/19 : COPY ./vendor/pi4j/Makefile /applications/builder/pi4j/pi4j-native/src/main/native
COPY failed: stat /var/lib/docker/tmp/docker-builder282844418/vendor/pi4j/Makefile: no such file or directory

**Comment by fguiet** [comment]
Hi @izhidov,

This is the way to use the Dockerfile (I tested it just now and it is working)

```bash
# Clone this repo
https://github.com/fguiet/automationserver-v2.git

# Go to builder folder
cd automationserver-v2/libpi4j/builder

# Build the image
docker build -t guiet/libpi4j:latest .
```

You can refer to the documentation for more information : <https://github.com/fguiet/automationserver-v2/blob/main/libpi4j/doc/building-libpi4j.md>

Fred
